# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redocly.com/docs/cli/ for more information.
reviews.yaml:
  operation-4xx-response:
    - '#/paths/~1settings~1github/get/responses'
