repos:
  - repo: https://github.com/betterleaks/betterleaks
    rev: v1.3.1
    hooks:
      - id: betterleaks-system

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.15
    hooks:
      - id: ruff-check
      - id: ruff-format

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.409
    hooks:
      - id: pyright

  - repo: https://github.com/jackdewinter/pymarkdown
    rev: v0.9.37
    hooks:
      - id: pymarkdown
        args:
          - --config=.pymarkdown.json
          - scan
        files: \.md$
