import { z } from "zod";
import { ReviewErrorSchema, ReviewFindingSchema, ReviewPerspective } from "./review.js";

/** The lead engineer's verdict on a single reviewer finding. */
export const DecisionVerdict = z.enum({
  ACCEPT: "accept",
  REJECT: "reject",
});
export type DecisionVerdict = z.infer<typeof DecisionVerdict>;

/** Final severity assigned to an individual finding. */
export const FindingSeverity = z.enum({
  CRITICAL: "critical",
  HIGH: "high",
  MEDIUM: "medium",
  LOW: "low",
});
export type FindingSeverity = z.infer<typeof FindingSeverity>;

/** Quality characteristic primarily affected by a finding. */
export const FindingImpact = z.enum({
  SECURITY: "security",
  CORRECTNESS: "correctness",
  PERFORMANCE: "performance",
  MAINTAINABILITY: "maintainability",
});
export type FindingImpact = z.infer<typeof FindingImpact>;

/** Final urgency assigned to an individual finding. */
export const FindingPriority = z.enum({
  HIGH: "high",
  MEDIUM: "medium",
  LOW: "low",
});
export type FindingPriority = z.infer<typeof FindingPriority>;

/**
 * LLM output schema for one finding decision.
 *
 * Uses a findingIndex reference instead of reproducing the full finding
 * object, which prevents data corruption from LLM re-serialisation. Calling
 * code resolves the index back to the original ReviewFinding.
 */
export const FindingDecisionOutputSchema = z.object({
  findingIndex: z.number().int(),
  verdict: DecisionVerdict,
  reason: z.string(),
  impact: z.string(),
  severity: FindingSeverity,
  impactCategory: FindingImpact,
  finalPriority: FindingPriority,
});
export type FindingDecisionOutput = z.infer<typeof FindingDecisionOutputSchema>;

/** Top-level LLM output schema passed to the structured-output call. */
export const LeadEngineerOutputSchema = z.object({
  overallSummary: z.string(),
  decisions: z.array(FindingDecisionOutputSchema).default([]),
});
export type LeadEngineerOutput = z.infer<typeof LeadEngineerOutputSchema>;

/**
 * Lead engineer's decision enriched with the original finding.
 *
 * `finding` holds the exact ReviewFinding object from the reviewer output —
 * it is never re-generated by the LLM.
 */
export const FindingDecisionSchema = z.object({
  reviewerId: z.string(),
  perspective: ReviewPerspective,
  finding: ReviewFindingSchema,
  verdict: DecisionVerdict,
  reason: z.string(),
  impact: z.string(),
  severity: FindingSeverity,
  impactCategory: FindingImpact,
  finalPriority: FindingPriority,
});
export type FindingDecision = z.infer<typeof FindingDecisionSchema>;

/** Final output of the Lead Engineer synthesis stage. */
export const LeadEngineerReportSchema = z.object({
  overallSummary: z.string(),
  decisions: z.array(FindingDecisionSchema).default([]),
  reviewerErrors: z.array(ReviewErrorSchema).default([]),
});
export type LeadEngineerReport = z.infer<typeof LeadEngineerReportSchema>;

// Severity/priority sort order is derived from the schemas' own declaration
// order (`.options`) rather than a hand-written parallel array, so the two
// can never drift.
const severityOrder = FindingSeverity.options;

function byVerdict(report: LeadEngineerReport, verdict: DecisionVerdict): FindingDecision[] {
  return report.decisions
    .filter((d) => d.verdict === verdict)
    .toSorted((a, b) => severityOrder.indexOf(a.severity) - severityOrder.indexOf(b.severity));
}

/** Accepted findings ordered by severity, highest first. */
export function acceptedDecisions(report: LeadEngineerReport): FindingDecision[] {
  return byVerdict(report, DecisionVerdict.enum.ACCEPT);
}

/** Rejected findings ordered by severity, highest first. */
export function rejectedDecisions(report: LeadEngineerReport): FindingDecision[] {
  return byVerdict(report, DecisionVerdict.enum.REJECT);
}

/**
 * Render the report as Markdown for chat output.
 *
 * Accepted findings are listed first, ordered by severity. Rejected findings
 * follow in severity order inside a collapsible `<details>` block. Reviewer
 * errors are appended at the end if present.
 */
export function toMarkdown(report: LeadEngineerReport): string {
  const lines: string[] = [
    "# Lead Engineer Review Report",
    "",
    "## Summary",
    "",
    report.overallSummary,
    "",
  ];

  const accepted = acceptedDecisions(report);
  if (accepted.length > 0) {
    lines.push(`## Accepted Findings (${accepted.length})`, "");
    accepted.forEach((d, i) => {
      let loc = "";
      if (d.finding.filePath) {
        loc = `\`${d.finding.filePath}\``;
        if (d.finding.line) {
          loc += ` L${d.finding.line}`;
        }
      }
      lines.push(
        `### ${i + 1}. [${d.severity.toUpperCase()}] ${loc || "(no location)"}`,
        "",
        `**Reviewer**: ${d.reviewerId} (${d.perspective})`,
        "",
        `**Finding**: ${d.finding.comment}`,
        "",
        `**Severity**: ${d.severity}`,
        "",
        `**Impact category**: ${d.impactCategory}`,
        "",
        `**Priority**: ${d.finalPriority}`,
        "",
        `**Impact if not fixed**: ${d.impact}`,
        "",
        `**Decision rationale**: ${d.reason}`,
      );
      if (d.finding.proposedFix) {
        lines.push("", `**Suggested fix**: ${d.finding.proposedFix}`);
      }
      lines.push("");
    });
  } else {
    lines.push("## Accepted Findings", "", "_No findings accepted._", "");
  }

  const rejected = rejectedDecisions(report);
  if (rejected.length > 0) {
    lines.push(
      `## Rejected Findings (${rejected.length})`,
      "",
      "<details>",
      "<summary>Expand to see rejected findings</summary>",
      "",
    );
    rejected.forEach((d, i) => {
      lines.push(
        `### ${i + 1}. ${d.finding.comment.slice(0, 80)}`,
        `- Reviewer: ${d.reviewerId}`,
        `- Reason: ${d.reason}`,
        "",
      );
    });
    lines.push("</details>", "");
  }

  if (report.reviewerErrors.length > 0) {
    lines.push("## Reviewer Errors", "");
    for (const err of report.reviewerErrors) {
      lines.push(`- \`${err.reviewerId}\` (${err.perspective}): ${err.message}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

/**
 * Prediction format consumed by `evaluation/tools/score_evaluation.py`
 * (`agent_predictions.jsonl`). Keys are snake_case on purpose: this is an
 * external wire contract with the Python evaluation pipeline, independent of
 * this module's internal camelCase field names.
 */
export interface EvaluationFormat {
  id: string;
  agent_findings: Array<{
    path: string;
    line: number;
    category: string;
    severity: string;
    impact: string;
    priority: string;
    summary: string;
  }>;
  lead_decisions: Array<{ path: string; line: number; decision: string }>;
}

function logDropped(prId: string, decision: FindingDecision, outputName: string): void {
  // Missing filePath/line is common enough with local models that it needs
  // to be visible instead of indistinguishable from "no findings" — see
  // docs/finding-location-silent-drop-spec.md.
  console.warn(
    `Dropping finding from ${outputName}: missing filePath/line ` +
      `(prId=${prId}, reviewerId=${decision.reviewerId}, comment=${JSON.stringify(
        decision.finding.comment.slice(0, 120),
      )})`,
  );
}

/** Serialise to the evaluation script's prediction format. */
export function toEvaluationFormat(report: LeadEngineerReport, prId: string): EvaluationFormat {
  const agentFindings: EvaluationFormat["agent_findings"] = [];
  for (const d of acceptedDecisions(report)) {
    if (d.finding.filePath && d.finding.line != null) {
      agentFindings.push({
        path: d.finding.filePath,
        line: d.finding.line,
        category: d.perspective,
        severity: d.severity,
        impact: d.impactCategory,
        priority: d.finalPriority,
        summary: d.finding.comment,
      });
    } else {
      logDropped(prId, d, "agent_findings");
    }
  }

  const leadDecisions: EvaluationFormat["lead_decisions"] = [];
  for (const d of report.decisions) {
    if (d.finding.filePath && d.finding.line != null) {
      leadDecisions.push({ path: d.finding.filePath, line: d.finding.line, decision: d.verdict });
    } else {
      logDropped(prId, d, "lead_decisions");
    }
  }

  return { id: prId, agent_findings: agentFindings, lead_decisions: leadDecisions };
}
