"""Pydantic models for the Lead Engineer synthesis stage.

Defines the decision schemas produced by the Lead Engineer agent after
evaluating the parallel reviewer outputs.  Kept separate from review-stage
models so the lead-stage contract can evolve independently.
"""

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, Field

from .review import ReviewError, ReviewFinding, ReviewPerspective, ReviewPriority


class DecisionVerdict(StrEnum):
    """The lead engineer's verdict on a single reviewer finding."""

    ACCEPT = "accept"
    REJECT = "reject"


class FindingDecisionOutput(BaseModel):
    """LLM output schema for one finding decision.

    Uses a finding_index reference instead of reproducing the full finding
    object, which prevents data corruption from LLM re-serialisation.
    The agent code resolves the index back to the original ReviewFinding.

    Attributes:
        finding_index: 1-based index matching the ``Finding #N`` label in the
            prompt built by ``_build_prompt_and_index``.
        verdict: Accept or reject decision.
        reason: Rationale for the decision.
        impact: Assessment of the impact if the finding is not fixed.
        final_priority: Lead engineer's final priority assignment; may differ
            from the reviewer's original priority.
    """

    finding_index: int = Field(..., description="1-based finding index from the prompt")
    verdict: DecisionVerdict = Field(..., description="Accept or reject")
    reason: str = Field(..., description="Rationale for the decision")
    impact: str = Field(..., description="Impact if not fixed")
    final_priority: ReviewPriority = Field(..., description="Final priority")


class LeadEngineerOutput(BaseModel):
    """Top-level LLM output schema passed to ``Agent.structured_output``.

    Attributes:
        overall_summary: High-level assessment of the PR's review findings.
        decisions: One decision per finding submitted to the lead engineer.
    """

    overall_summary: str = Field(..., description="High-level assessment")
    decisions: list[FindingDecisionOutput] = Field(
        default_factory=list, description="One decision per finding"
    )


class FindingDecision(BaseModel):
    """Lead engineer's decision enriched with the original finding.

    Created by the agent code after resolving ``FindingDecisionOutput.
    finding_index`` against the prompt's index map.  The ``finding`` field
    contains the exact ``ReviewFinding`` object from the reviewer output —
    it is never re-generated by the LLM.

    Attributes:
        reviewer_id: Identifier of the reviewer that raised the finding.
        perspective: Review perspective the finding came from.
        finding: The original finding being decided.
        verdict: Accept or reject decision.
        reason: Rationale for the decision.
        impact: Assessment of the impact if not fixed.
        final_priority: Lead engineer's final priority.
    """

    reviewer_id: str = Field(..., description="Reviewer identifier")
    perspective: ReviewPerspective = Field(..., description="Review perspective")
    finding: ReviewFinding = Field(..., description="Original finding")
    verdict: DecisionVerdict = Field(..., description="Accept or reject")
    reason: str = Field(..., description="Rationale for the decision")
    impact: str = Field(..., description="Impact if not fixed")
    final_priority: ReviewPriority = Field(..., description="Final priority")


class LeadEngineerReport(BaseModel):
    """Final output of the Lead Engineer synthesis stage.

    Attributes:
        overall_summary: High-level assessment of the PR's review findings.
        decisions: All decisions, one per finding evaluated.
        reviewer_errors: Errors forwarded from the parallel review stage for
            visibility; the lead engineer does not act on them.
    """

    overall_summary: str = Field(..., description="High-level assessment")
    decisions: list[FindingDecision] = Field(
        default_factory=list, description="All decisions"
    )
    reviewer_errors: list[ReviewError] = Field(
        default_factory=list,
        description="Errors forwarded from the parallel review stage",
    )

    def accepted(self) -> list[FindingDecision]:
        """Return accepted findings sorted CRITICAL → HIGH → MEDIUM → LOW.

        Returns:
            Accepted findings in descending priority order.
        """
        return self._by_verdict(DecisionVerdict.ACCEPT)

    def rejected(self) -> list[FindingDecision]:
        """Return rejected findings sorted CRITICAL → HIGH → MEDIUM → LOW.

        Returns:
            Rejected findings in descending priority order.
        """
        return self._by_verdict(DecisionVerdict.REJECT)

    def _by_verdict(self, verdict: DecisionVerdict) -> list[FindingDecision]:
        order = list(ReviewPriority)
        return sorted(
            [d for d in self.decisions if d.verdict is verdict],
            key=lambda d: order.index(d.final_priority),
        )

    def to_markdown(self) -> str:
        """Render the report as Markdown for chat output.

        Accepted findings are listed first, sorted by final_priority.
        Rejected findings follow inside a collapsible ``<details>`` block.
        Reviewer errors are appended at the end if present.

        Returns:
            Markdown-formatted string suitable for a chat interface.
        """
        lines: list[str] = [
            "# Lead Engineer Review Report",
            "",
            "## Summary",
            "",
            self.overall_summary,
            "",
        ]

        accepted = self.accepted()
        if accepted:
            lines += [f"## Accepted Findings ({len(accepted)})", ""]
            for i, d in enumerate(accepted, 1):
                loc = ""
                if d.finding.file_path:
                    loc = f"`{d.finding.file_path}`"
                    if d.finding.line:
                        loc += f" L{d.finding.line}"
                lines += [
                    f"### {i}. [{d.final_priority.upper()}] {loc or '(no location)'}",
                    "",
                    f"**Reviewer**: {d.reviewer_id} ({d.perspective.value})",
                    "",
                    f"**Finding**: {d.finding.comment}",
                    "",
                    f"**Impact**: {d.impact}",
                    "",
                    f"**Decision rationale**: {d.reason}",
                ]
                if d.finding.proposed_fix:
                    lines += ["", f"**Suggested fix**: {d.finding.proposed_fix}"]
                lines.append("")
        else:
            lines += ["## Accepted Findings", "", "_No findings accepted._", ""]

        rejected = self.rejected()
        if rejected:
            lines += [
                f"## Rejected Findings ({len(rejected)})",
                "",
                "<details>",
                "<summary>Expand to see rejected findings</summary>",
                "",
            ]
            for i, d in enumerate(rejected, 1):
                lines += [
                    f"### {i}. {d.finding.comment[:80]}",
                    f"- Reviewer: {d.reviewer_id}",
                    f"- Reason: {d.reason}",
                    "",
                ]
            lines += ["</details>", ""]

        if self.reviewer_errors:
            lines += ["## Reviewer Errors", ""]
            for err in self.reviewer_errors:
                lines.append(
                    f"- `{err.reviewer_id}` ({err.perspective.value}): {err.message}"
                )
            lines.append("")

        return "\n".join(lines)

    def to_evaluation_format(self, pr_id: str) -> dict[str, Any]:
        """Serialise to the evaluation script's prediction format.

        Args:
            pr_id: PR identifier in ``owner/repo#number`` format.

        Returns:
            Dict compatible with the ``agent_predictions.jsonl`` schema used by
            ``evaluation/tools/score_evaluation.py``.
        """
        agent_findings = [
            {
                "path": d.finding.file_path or "",
                "line": d.finding.line or 1,
                "category": d.perspective.value,
                "severity": d.final_priority.value,
                "summary": d.finding.comment,
            }
            for d in self.accepted()
            if d.finding.file_path is not None
        ]
        lead_decisions = [
            {
                "path": d.finding.file_path or "",
                "line": d.finding.line or 1,
                "decision": d.verdict.value,
            }
            for d in self.decisions
            if d.finding.file_path is not None
        ]
        return {
            "id": pr_id,
            "agent_findings": agent_findings,
            "lead_decisions": lead_decisions,
        }
